name: Unity License Activation

on:
  workflow_dispatch:

jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        with:
          unityVersion: '2022.3.20f1' # Replace with your Unity version
