name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-dotnet:
    name: Build .NET Project on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build C# Project
        run: dotnet build ./quantum_code/quantum.code/quantum.code.csproj /p:Configuration=Release

      - name: Archive Entire Repository
        uses: actions/upload-artifact@v3
        with:
          name: repo-content
          path: .

  build-unity:
    name: Build Unity Project on Ubuntu
    needs: build-dotnet
    runs-on: ubuntu-latest
    steps:
      - name: Download Entire Repository
        uses: actions/download-artifact@v3
        with:
          name: repo-content
          path: .

      # Here, add your steps for the Unity build process
      - name: Cache for Unity
        uses: actions/cache@v3
        with:
          path: ./quantum_unity/Library
          key: Library-${{ hashFiles('./quantum_unity/Assets/**', './quantum_unity/Packages/**', './quantum_unity/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./quantum_unity
          targetPlatform: StandaloneWindows # Adjust the target platform as needed

      - name: Upload Unity Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Unity-Build
          path: path/to/your/unity/build/output # Replace with the path to your Unity build output
