name: Actions 😎

on:
  workflow_dispatch:

jobs:
  build-dotnet:
    name: Build .NET Project
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.8' # Ensure .NET Framework 4.8 is used

      - name: Build C# Project
        run: dotnet build ./quantum_code/quantum.code/quantum.code.csproj /p:Configuration=Release

      # You can add steps to upload build artifacts if needed

  build-unity:
    name: Build Unity Project
    needs: build-dotnet
    runs-on: ubuntu-latest
    steps:
      # You can add steps to download build artifacts from the dotnet job if needed

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache for Unity
      - uses: actions/cache@v3
        with:
          path: ./quantum_unity/Library
          key: Library-${{ hashFiles('./quantum_unity/Assets/**', './quantum_unity/Packages/**', './quantum_unity/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./quantum_unity
          targetPlatform: StandaloneWindows64

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
